In [5]:
import sqlite3

# conectando...
conn = sqlite3.connect('banco_dados.db')

# definindo um cursor
cursor = conn.cursor()

def criar_tabela():

  # criando a tabela (schema)
  cursor.execute("""
  CREATE TABLE produto (
        id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
        data TEXT,
        nome TEXT NOT NULL,
        valor real
  );
  """)
  
  # Conclusão da criação da tabela
  print('Tabela criada com sucesso.')

  # desconectando...
  conn.close()

def inserir_dados():
  data = input("Data da compra: ")
  nome = input("Nome do produto: ")
  valor = input("Valor do produto em reais R$: ")

  cursor.execute("INSERT INTO produto VALUES (%s, %s, %s)", (data, nome, valor))

  # gravando no banco 
  conn.commit()

  print('Dados inseridos com sucesso.')

  conn.close()

def listar_dados():

  # lendo os dados de todos os produtos
  cursor.execute("""
  SELECT * FROM produto;
  """)

  for linha in cursor.fetchall():
      print(linha)

  conn.close()

def atualizar_dados():
  valor = 140.00

  # alterando os dados da tabela produto
  cursor.execute("""
  UPDATE produto
  SET valor = ?
  WHERE valor = 98.00
  """, (valor))

  conn.commit()

  print('Dados atualizados com sucesso.')

  conn.close()


def remover_dados():
  valor = 62.00
  
  # excluindo registros da tabela produto

  cursor.execute("""
  DELETE * FROM produto
  WHERE id = ?
  """, (valor))

  conn.commit()

  print('Registro excluido com sucesso.')

  conn.close()

In [ ]:
#Criação da tabela produto
criar_tabela()

# Menu para escolha de opções e manuseio da tabela
op = 0
while op != 5:
  print ('''Menu de Opções
  [1] - Inserir dado
  [2] - Listar dados
  [3] - Atualizar dados
  [4] - Deletar dados
  [5] - Sair''')

  op = int( input( 'Digite a opção desejada: ' ) )

  if (op == 1):
    inserir_dados()
  elif (op == 2):
    listar_dados()
  elif (op == 3):
    atualizar_dados()
  elif (op == 4):
    remover_dados()
  else:
    print('Fim do programa de salários')